version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY_HEADERS: "xforwarded"
      KC_DB: dev-file
    ports:
      - "8080:8080"
    volumes:
      # Questa riga salva gli UTENTI direttamente in una cartella del tuo progetto!
      - ./keycloak_sqlite_data:/opt/keycloak/data
      # Questa riga carica i RUOLI e i CLIENT dal tuo file json
      - ./realm-export.json:/opt/keycloak/data/import/realm.json
    command:
      - start-dev
      - --import-realm